### ISSUE TITLE
Implement filter algorithms

### ISSUE THREAD

**Issue by vuvuong003** [hsalway1/WolfJobs#4]
Implement filter algorithms to help users easily find specific applications based on various criteria (ex. job name, position, salary, company name)

**Comment by hsalway1** [comment]
Implemented filter algorithms in https://github.com/hsalway1/WolfJobs/pull/16 and https://github.com/hsalway1/WolfJobs/pull/17. Closing the issue.

**Comment by hsalway1** [comment]
Implemented filter algorithms in https://github.com/hsalway1/WolfJobs/pull/16 and https://github.com/hsalway1/WolfJobs/pull/17. Closing the issue.
